
AGELANG['ru'] = {
    'search': 'поиск',
    'lupd': 'актуально на ',
    'object': 'Объект',
    'object-s': 'Объекта(ов)',
    'youcanaddnew': 'если вам известны координаты этой системы, внесите их в базу данных',
    'foundaprox': 'найдено примерно',
    'objecttype': 'Тип объекта',
    'align': 'Принадлежность',
    'object-all-': 'Не определено',
    'object-all-independent': 'Независимые',
    'object-all-federation': 'Федерация',
    'object-all-alliance': 'Альянс',
    'objecttypesub': 'Субтип объекта',
    'objectfuel': 'можно заправиться',
    'objectbbs': 'bulletin board',
    'objectbm': 'black market',
    'objectcomm': 'commodities market',
    'objectship': 'shipyard',
    'objectoutfit': 'outfitting',
    'map': 'карта',
    'project': 'проект',
    'conception': 'концепция',
    'rules': 'правила',
    'statistic': 'статистика',
    'reporting': 'отчетность',
    'api': 'api',
    'feedback': 'Обратная связь',
    'donate': 'пожертвовать',
    'backemail': 'Ваш email',
    'question': 'Вопрос',
    'send': 'Отправить',
    'snx': 'Спасибо',
    'result': 'результат',
    'system': 'система',
    'addsystem': 'добавить систему',
    'systemobject': 'объекты системы',
    'desired_object': 'искомый объект',
    'noresult': 'пустой результат',
    'norecords': 'нет записей',
    'distance': 'расстояние',
    'conception_text': '<p>Association of Galaxy Exploration - проект по сбору, актуализации и предоставлению информации о звездных системах и их объектах в Галактике &quot;ELITE: Dangerous&quot;.</p><p>Данный проект призван собрать информацию о всех звездных системах доступных и не доступных для посещения пилотами.</p><p>Каждый пилот может внести посильный вклад в наполнение или актуализацию информации о звездных системах и их объектах.</p><p>Вся информация предоставляется по принципу &quot;как есть&quot; - и не может являться объективной в решении споров и разбирательств любого уровня.&nbsp;Однако, отсылка на ресурс, как на источник информации, приветствуется.</p>',
    'rules_text': ''
};
