AGELANG['en'] = {
    'search': 'search',
    'lupd': 'true on ',
    'object': 'object',
    'object-s': 'object(s)',
    'youcanaddnew': 'If you know the coordinates of the system, make them into a database',
    'foundaprox': 'found approximately',
    'objecttype': 'object type',
    'align': 'alignment',
    'object-all-': 'not set',
    'object-all-independent': 'independent',
    'object-all-federation': 'federation',
    'object-all-alliance': 'alliance',
    'object-type-star': 'Star',
    'object-type-beacon': 'Beacon',
    'object-type-asteroidring': 'Asteroid ring',
    'object-type-planet': 'Planet',
    'object-type-station': 'Station',
    'objecttypesub': 'object subtype',
    'objectfuel': 'can fuel',
    'objectbbs': 'bulletin board',
    'objectbm': 'black market',
    'objectcomm': 'commodities market',
    'objectship': 'shipyard',
    'objectoutfit': 'outfitting',
    'map': 'map',
    'project': 'project',
    'conception': 'conception',
    'rules': 'rules',
    'statistic': 'statistic',
    'reporting': 'reporting',
    'api': 'api',
    'feedback': 'feedback',
    'donate': 'donate',
    'backemail': 'you email',
    'question': 'question',
    'send': 'send',
    'snx': 'thank you',
    'result': 'result',
    'system': 'system',
    'addsystem': 'add system',
    'systemobject': 'system objects',
    'desired_object': 'desired object',
    'noresult': 'no result',
    'norecords': 'no records',
    'distance': 'distance',
    'conception_text': '<p>Association of Galaxy Exploration - a project to collect, update and provide information about stellar systems and their objects in the Galaxy, &quot;ELITE: Dangerous&quot;.&nbsp;</p><p>This project aims to collect information on all star systems available and not available for visiting pilots.&nbsp;</p><p>Each pilot can make a contribution to filling or updating information about stellar systems and their properties.&nbsp;</p><p>All information provided &quot;as is&quot; - and can not be objective in resolving disputes and proceedings at any level. However, a reference to a resource, as a source of information is encouraged.</p>',
    'profile': 'profile',
    'token': 'token',
    'abouttoken': 'token - used for authorization at the request of the pilot to make or change data',
    'password': 'password',
    'logout': 'logout',
    'authorization': 'authorization',
    'registration': 'registration'
};
